spring:
  application:
    name: prodigal-service
  datasource:
    url: jdbc:mysql://mysql:3306/database
    hikari:
      username: root
      password: root
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect